import type { Metadata } from "next";
import { Fira_Sans } from "next/font/google";
import "./globals.css";
import { NavBar } from "./components/NavBar/NavBar";
import { Footer } from "./components/Footer/Footer";
import { ProductsProvider } from "./context/ProductsContext";
import CartProvider from "./context/CartContext";

const fira = Fira_Sans({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fira.className} suppressHydrationWarning={true}>
        <CartProvider>
          <NavBar />
          <ProductsProvider>
            {children}
          </ProductsProvider>
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
